spring:
  datasource:
    driver-class-name: org.h2.Driver

  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
    database-platform: org.hibernate.dialect.H2Dialect
  threads:
    virtual:
      enabled: true


rsa-key:
  public-key:
  private-key:

server:
  forward-headers-strategy: native
  port: 9000


logging:
  level:
    root: INFO
    org.springframework.web: DEBUG
    org.springframework.security: DEBUG
    org.springframework.security.oauth2: DEBUG
