services:
  postgres:
    container_name: postgres
    image: postgres:latest
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PW}
      - POSTGRES_DB=${POSTGRES_DB}
    ports:
      - "5433:5432"
    user: ${POSTGRES_USER}
    restart: always
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready" ]
      interval: 10s
      timeout: 5s
      retries: 5
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
      - postgres-data:/var/lib/postgresql/data
  redis:
    container_name: redis
    image: redis:latest
    ports:
      - "6380:6379"
    restart: always
    volumes:
      - redis-data:/data
  #  Uncomment once you have the local image built
  auth-server:
    container_name: authorization-server
    image: authorization-server:latest
    environment:
      - DATASOURCE_URL=jdbc:postgresql://postgres:5432/oauth_nowhere
      - DB_USERNAME=${POSTGRES_USER}
      - DB_PASSWORD=${POSTGRES_PW}
      - PRIVATE_KEY=${PRIVATE_KEY}
      - PUBLIC_KEY=${PUBLIC_KEY}
      - GITHUB_CLIENT_ID=${GITHUB_CLIENT_ID}
      - GITHUB_CLIENT_SECRET=${GITHUB_CLIENT_SECRET}
      - GOOGLE_CLIENT_ID=${GOOGLE_CLIENT_ID}
      - GOOGLE_CLIENT_SECRET=${GOOGLE_CLIENT_SECRET}
      - REDIS_HOST=${REDIS_HOST}
      - REDIS_PORT=${REDIS_PORT}
      - REDIS_PW=${REDIS_PW}
    ports:
      - "9000:9000"
    restart: always
    depends_on:
      - postgres
  nginx:
    image: nginx:latest
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    restart: always
    depends_on:
      - auth-server
#  pgadmin:
#    container_name: pgadmin
#    image: dpage/pgadmin4:latest
#    environment:
#      - PGADMIN_DEFAULT_EMAIL=${PGADMIN_EMAIL}
#      - PGADMIN_DEFAULT_PASSWORD=${PGADMIN_PW}
#    ports:
#      - "5050:80"
#    restart: always
#    volumes:
#      - pgadmin-data:/var/lib/pgadmin
volumes:
  postgres-data:
  pgadmin-data:
  redis-data:
